name: 'Setup PHP environment'
description: 'Setup a PHP environment and add it to the PATH, additionally providing proxy support'
author: 'nanasess'
branding:
  color: purple
  icon: code
inputs:
  php-version:
    description: 'Version Spec of the version to use.  Examples: 8.1'
    default: '8.3'
  scope:
    description: 'Optional scope for authenticating against scoped registries'
runs:
  using: 'node20'
  main: 'dist/index.js'
